Техническое задание 8
adrzdv/java-kanban pull request #4
Opened 2024-06-22 17:37 UTC by adrzdv

Реализован функционал в соответствии с ТЗ, переписаны методы для работы с задачами, исправлены методы перевода задач в строку и обратно

2024-06-23 17:37 UTC, kriwsha requested changes

2024-06-23 17:37 UTC, kriwsha commented on src/TaskManager/InMemoryTaskManager.java
> +        return this.sortedTaskSet = treeSetTask;
Так делать не стоит. Если хотите присваивать результат полю класса, сделайте это отдельный операцией. Но тут точно нужно хранить эту коллекцию? А во-вторых, что вы возвращаете? Коллекцию или результат выполнения операции присвоения? Для Java это, конечно, одно и то же, но в будущем, если вы захотите рассмотреть другие языки, то там может быть очень неожиданный результат.

2024-06-23 17:37 UTC, kriwsha commented on src/TaskManager/FileBackedTaskManager.java
>              return null;
Здесь не следует возвращать null. У вас не инициализировался объект - это следует сделать исключением.

2024-06-23 17:37 UTC, kriwsha commented on src/TaskManager/InMemoryTaskManager.java
> +    private static final LocalDateTime DEFAULT_DATE = LocalDateTime.of(1900, 01, 01, 00, 00);
Статические финальные переменные следует перенести в самое начало класса

2024-06-23 19:33 UTC, adrzdv commented on src/TaskManager/InMemoryTaskManager.java
> +        return this.sortedTaskSet = treeSetTask;
По поводу выделения в отдельную операцию присвоения значения полю - да, согласен, немного упустил этот момент, исправлю.  По поводу хранения коллекции - думаю, что да, хранить ее стоит, поскольку согласно ТЗ данный список будет запрашиваться часто пользователем.

2024-06-24 18:51 UTC, kriwsha approved these changes

2024-06-24 18:53 UTC, merged